pipeline {
    agent any
    stages {
        stage('Prepare') {
            steps {
                git branch: 'mlops', url: 'https://github.com/JokerRd/find_ad_in_image.git'
                sh "python -m pip install --upgrade -r requirements.txt"
            }
        }
        stage('Lint') {
            steps {
                sh 'flake8'
            }
        }
        stage('Test') {
            steps {
                sh 'cd source && pytest'
            }
        }
        stage('Image build') {
            steps {
                    script {
                        docker.build 'image_parser/app'
                    }
            }
        }
    }
}